# This file contains all available configuration options
# with their default values.
version: "2"

# options for analysis running
run:
  tests: false

linters:
  disable:
    - lll
    - funlen
    - varnamelen
    - exhaustruct
    - tagliatelle
    - errcheck
