before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    goarm:
      - 7
    main: ./cmd/m1-terraform-provider-helper
  
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else }}{{ .Os }}{{ end }}_{{ .Arch }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc

brews:
  - tap:
      owner: kreuzwerker
      name: homebrew-taps
      token: "{{ .Env.GORELEASER_TOKEN }}"
    dependencies:
      - name: go
    download_strategy: CurlDownloadStrategy
    homepage: "https://github.com/kreuzwerker/m1-terraform-provider-helper"
    description: "CLI to support with downloading and compiling terraform providers for Mac with M1 chip."
